import { pool,withContext } from "./db.js";
import { config } from "./config.js";
import { randomToken,tokenHash } from "./security.js";
export const COOKIE_NAME=config.nodeEnv==="production"?"__Host-mm_session":"mm_session";
export async function revokePresentedSession(request){const raw=request.cookies?.[COOKIE_NAME];if(raw)await pool.query("UPDATE sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE token_hash=$1",[tokenHash(raw)]);}
export async function createSession({reply,userId,activeSchoolId,securityVersion,userAgent,ip}){const raw=randomToken(32),csrf=randomToken(32);await pool.query(`INSERT INTO sessions(token_hash,csrf_hash,user_id,active_school_id,security_version,expires_at,idle_expires_at,user_agent_hash,ip_hash) VALUES($1,$2,$3,$4,$5,now()+($6||' hours')::interval,now()+($7||' minutes')::interval,encode(digest($8,'sha256'),'hex'),encode(digest($9,'sha256'),'hex'))`,[tokenHash(raw),tokenHash(csrf),userId,activeSchoolId||null,securityVersion,String(config.sessionTtlHours),String(config.sessionIdleMinutes),userAgent||"",ip||""]);reply.setCookie(COOKIE_NAME,raw,{httpOnly:true,secure:config.nodeEnv==="production",sameSite:"strict",path:"/",maxAge:config.sessionTtlHours*3600});return csrf;}
export async function loadSession(request){const raw=request.cookies?.[COOKIE_NAME];if(!raw)return null;const {rows}=await pool.query(`SELECT s.id session_id,s.csrf_hash,s.user_id,s.active_school_id,s.step_up_until,s.security_version,u.full_name,u.login,u.email,u.account_state,u.security_version user_security_version FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND s.idle_expires_at>now() LIMIT 1`,[tokenHash(raw)]);const r=rows[0];if(!r||["DISABLED","LOCKED"].includes(r.account_state)||r.security_version!==r.user_security_version)return null;let roles=[];if(r.active_school_id){roles=await withContext({userId:r.user_id,schoolId:r.active_school_id},async c=>(await c.query(`SELECT mr.role FROM membership_roles mr JOIN school_memberships sm ON sm.school_id=mr.school_id AND sm.user_id=mr.user_id WHERE mr.school_id=$1 AND mr.user_id=$2 AND sm.status='ACTIVE' ORDER BY mr.role`,[r.active_school_id,r.user_id])).rows.map(x=>x.role));if(!roles.length)await pool.query("UPDATE sessions SET active_school_id=NULL WHERE id=$1",[r.session_id]);}
await pool.query(`UPDATE sessions SET last_seen_at=now(),idle_expires_at=LEAST(expires_at,now()+($2||' minutes')::interval) WHERE id=$1`,[r.session_id,String(config.sessionIdleMinutes)]);return{sessionId:r.session_id,csrfHash:r.csrf_hash,userId:r.user_id,schoolId:roles.length?r.active_school_id:null,stepUpUntil:r.step_up_until,fullName:r.full_name,login:r.login,email:r.email,accountState:r.account_state,roles};}
export async function destroySession(request,reply){await revokePresentedSession(request);reply.clearCookie(COOKIE_NAME,{path:"/"});}
export function steppedUp(auth){return!!auth?.stepUpUntil&&new Date(auth.stepUpUntil).getTime()>Date.now();}
