import { withContext } from "../db.js";
import { audit } from "../audit.js";
import { buildStudentReport } from "../services/reports.js";
import { isUuid,num,text } from "../validators.js";

export async function registerAcademicRoutes(app,{requireSession,requireMutation}){
  app.get("/api/classes",async(request,reply)=>{if(!(await requireSession(request,reply)))return;if(!request.auth.schoolId)return{classes:[]};return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>({classes:(await c.query("SELECT id,name,level,section FROM classes WHERE active ORDER BY name")).rows}));});

  app.get("/api/classes/:classId/students",async(request,reply)=>{if(!(await requireSession(request,reply)))return;const classId=String(request.params.classId||"");if(!request.auth.schoolId||!isUuid(classId))return reply.code(400).send({error:"INVALID_CLASS"});return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>{if(!(await c.query("SELECT 1 FROM classes WHERE id=$1 AND school_id=$2",[classId,request.auth.schoolId])).rowCount)return reply.code(404).send({error:"CLASS_NOT_FOUND"});return {students:(await c.query("SELECT id,student_uid,full_name,gender,birth_date,status,row_version FROM students WHERE class_id=$1 ORDER BY full_name",[classId])).rows};});});

  app.get("/api/classes/:classId/subjects",async(request,reply)=>{if(!(await requireSession(request,reply)))return;const classId=String(request.params.classId||"");if(!request.auth.schoolId||!isUuid(classId))return reply.code(400).send({error:"INVALID_CLASS"});return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>{if(!(await c.query("SELECT 1 FROM classes WHERE id=$1 AND school_id=$2",[classId,request.auth.schoolId])).rowCount)return reply.code(404).send({error:"CLASS_NOT_FOUND"});return {subjects:(await c.query(`SELECT DISTINCT s.id,s.name,s.coefficient,s.max_score FROM subjects s WHERE s.active AND (app.has_role('DIRECTOR') OR app.has_permission('SUBJECT_READ',$1,s.id) OR app.has_permission('GRADE_READ',$1,s.id) OR app.has_permission('GRADE_WRITE',$1,s.id) OR EXISTS(SELECT 1 FROM grades g WHERE g.subject_id=s.id AND g.class_id=$1 AND app.is_guardian_of(g.student_id))) ORDER BY s.name`,[classId])).rows};});});

  app.get("/api/classes/:classId/grades",async(request,reply)=>{if(!(await requireSession(request,reply)))return;const classId=String(request.params.classId||"");if(!request.auth.schoolId||!isUuid(classId))return reply.code(400).send({error:"INVALID_CLASS"});return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>{if(!(await c.query("SELECT 1 FROM classes WHERE id=$1 AND school_id=$2",[classId,request.auth.schoolId])).rowCount)return reply.code(404).send({error:"CLASS_NOT_FOUND"});return {grades:(await c.query("SELECT id,student_id,subject_id,term,assessment,score,version,updated_at FROM grades WHERE class_id=$1 ORDER BY student_id,subject_id,term,assessment",[classId])).rows};});});

  app.post("/api/grades",async(request,reply)=>{if(!(await requireMutation(request,reply)))return;if(!request.auth.schoolId)return reply.code(403).send({error:"SCHOOL_REQUIRED"});const b=request.body||{},classId=String(b.classId||""),studentId=String(b.studentId||""),subjectId=String(b.subjectId||""),term=String(b.term||"").toUpperCase(),assessment=text(b.assessment||"MAIN",{min:1,max:60}),score=num(b.score,{min:0,max:100000});if(!isUuid(classId)||!isUuid(studentId)||!isUuid(subjectId)||!["T1","T2","T3"].includes(term)||!assessment||score===null)return reply.code(400).send({error:"INVALID_GRADE"});return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>{if(!(await c.query("SELECT app.has_permission('GRADE_WRITE',$1,$2) ok",[classId,subjectId])).rows[0].ok)return reply.code(403).send({error:"ACCESS_DENIED"});if(!(await c.query("SELECT 1 FROM students WHERE id=$1 AND class_id=$2 AND school_id=$3",[studentId,classId,request.auth.schoolId])).rowCount)return reply.code(404).send({error:"STUDENT_NOT_FOUND"});const subject=await c.query("SELECT max_score FROM subjects WHERE id=$1 AND school_id=$2",[subjectId,request.auth.schoolId]);const max=Number(subject.rows[0]?.max_score);if(!Number.isFinite(max)||score>max)return reply.code(400).send({error:"INVALID_SCORE"});try{const q=await c.query(`INSERT INTO grades(school_id,class_id,student_id,subject_id,term,assessment,score,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,version`,[request.auth.schoolId,classId,studentId,subjectId,term,assessment,score,request.auth.userId]);await c.query("INSERT INTO grade_history(grade_id,school_id,old_score,new_score,old_version,new_version,changed_by) VALUES($1,$2,NULL,$3,NULL,$4,$5)",[q.rows[0].id,request.auth.schoolId,score,q.rows[0].version,request.auth.userId]);await audit(c,request.auth,"GRADE_CREATED","grade",q.rows[0].id,{studentId,subjectId,term,assessment});return reply.code(201).send({ok:true,...q.rows[0]});}catch(e){if(e?.code==="23505")return reply.code(409).send({error:"GRADE_ALREADY_EXISTS"});if(e?.code==="23503")return reply.code(400).send({error:"GRADE_SCOPE_MISMATCH"});throw e;}});});

  app.put("/api/grades/:gradeId",async(request,reply)=>{if(!(await requireMutation(request,reply)))return;const gradeId=String(request.params.gradeId||""),b=request.body||{},expected=num(b.version,{min:1,max:1e9}),score=num(b.score,{min:0,max:100000});if(!request.auth.schoolId||!isUuid(gradeId)||expected===null||score===null)return reply.code(400).send({error:"INVALID_GRADE"});return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>{const current=await c.query(`SELECT g.id,g.score,g.version,g.subject_id,s.max_score FROM grades g JOIN subjects s ON s.id=g.subject_id WHERE g.id=$1`,[gradeId]);const row=current.rows[0];if(!row)return reply.code(404).send({error:"GRADE_NOT_FOUND"});if(score>Number(row.max_score))return reply.code(400).send({error:"INVALID_SCORE"});const q=await c.query(`UPDATE grades SET score=$1,version=version+1,updated_by=$2,updated_at=now() WHERE id=$3 AND version=$4 RETURNING id,version`,[score,request.auth.userId,gradeId,expected]);if(!q.rowCount)return reply.code(409).send({error:"VERSION_CONFLICT"});await c.query("INSERT INTO grade_history(grade_id,school_id,old_score,new_score,old_version,new_version,changed_by) VALUES($1,$2,$3,$4,$5,$6,$7)",[gradeId,request.auth.schoolId,row.score,score,row.version,q.rows[0].version,request.auth.userId]);await audit(c,request.auth,"GRADE_UPDATED","grade",gradeId,{oldScore:row.score,newScore:score,newVersion:q.rows[0].version});return{ok:true,...q.rows[0]};});});

  app.get("/api/guardian/students",async(request,reply)=>{if(!(await requireSession(request,reply)))return;if(!request.auth.schoolId)return{students:[]};return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>({students:(await c.query(`SELECT s.id,s.student_uid,s.full_name,s.gender,s.class_id,c.name class_name FROM guardian_student_links gsl JOIN students s ON s.id=gsl.student_id JOIN classes c ON c.id=s.class_id WHERE gsl.guardian_user_id=$1 AND gsl.active=true ORDER BY s.full_name`,[request.auth.userId])).rows}));});

  app.get("/api/students/:studentId/report",async(request,reply)=>{if(!(await requireSession(request,reply)))return;const studentId=String(request.params.studentId||"");if(!request.auth.schoolId||!isUuid(studentId))return reply.code(400).send({error:"INVALID_STUDENT"});return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>{const sq=await c.query(`SELECT s.id,s.student_uid,s.full_name,s.gender,s.class_id,c.name class_name FROM students s JOIN classes c ON c.id=s.class_id WHERE s.id=$1`,[studentId]);const student=sq.rows[0];if(!student)return reply.code(404).send({error:"STUDENT_NOT_FOUND"});const subjects=(await c.query(`SELECT DISTINCT sub.id,sub.name,sub.coefficient,sub.max_score FROM subjects sub JOIN grades g ON g.subject_id=sub.id WHERE g.student_id=$1 ORDER BY sub.name`,[studentId])).rows;const grades=(await c.query(`SELECT student_id,subject_id,term,assessment,score FROM grades WHERE student_id=$1 ORDER BY subject_id,term,assessment`,[studentId])).rows;const settings=(await c.query("SELECT annual_weight_t1,annual_weight_t2,annual_weight_t3 FROM school_settings WHERE school_id=$1",[request.auth.schoolId])).rows[0]||{};const report=buildStudentReport({subjects,grades,weights:{T1:Number(settings.annual_weight_t1||1),T2:Number(settings.annual_weight_t2||2),T3:Number(settings.annual_weight_t3||3)}});return{student,report};});});

  app.get("/api/notifications",async(request,reply)=>{if(!(await requireSession(request,reply)))return;return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>({notifications:(await c.query("SELECT id,kind,title,body,read_at,created_at FROM in_app_notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50",[request.auth.userId])).rows}));});
  app.post("/api/notifications/:id/read",async(request,reply)=>{if(!(await requireMutation(request,reply)))return;const id=String(request.params.id||"");if(!isUuid(id))return reply.code(400).send({error:"INVALID_NOTIFICATION"});return withContext({userId:request.auth.userId,schoolId:request.auth.schoolId},async c=>{await c.query("UPDATE in_app_notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND user_id=$2",[id,request.auth.userId]);return{ok:true};});});
}
