import { pool,withContext } from "../db.js";
import { config } from "../config.js";
import { audit } from "../audit.js";
import { createSession,destroySession,revokePresentedSession } from "../auth.js";
import { hashPassword,verifyPassword,normalizeLogin,normalizeEmail,validPassword,randomToken,tokenHash,safeEqualText } from "../security.js";
import { isUuid,text,optionalText,oneOf } from "../validators.js";
import { PERMISSIONS } from "../permissions.js";

export async function registerAuthRoutes(app,{requireSession,requireMutation}){
  const dummyPasswordHash=await hashPassword("this-is-a-dummy-password-used-only-for-timing-equalization");

  app.get("/api/setup/status",async()=>{const {rows}=await pool.query("SELECT EXISTS(SELECT 1 FROM schools) configured");return{configured:!!rows[0]?.configured};});

  app.post("/api/setup/bootstrap",{config:{rateLimit:{max:3,timeWindow:"1 hour"}}},async(request,reply)=>{
    const secret=String(request.headers["x-bootstrap-secret"]||"");
    if(!config.bootstrapSecret||!safeEqualText(secret,config.bootstrapSecret))return reply.code(403).send({error:"BOOTSTRAP_DENIED"});
    const b=request.body||{};const login=normalizeLogin(b.login),email=normalizeEmail(b.email),fullName=text(b.fullName,{min:2,max:150}),password=String(b.password||""),schoolName=text(b.schoolName,{min:2,max:180}),schoolType=oneOf(b.schoolType,["PUBLIC","PRIVATE"]),academicYear=text(b.academicYear||"2026/2027",{min:4,max:20});
    if(!login||login.length<3||!fullName||!validPassword(password)||!schoolName||!schoolType||!academicYear)return reply.code(400).send({error:"INVALID_BOOTSTRAP_DATA"});
    const client=await pool.connect();try{await client.query("BEGIN");await client.query("SELECT pg_advisory_xact_lock(hashtext('ma_madrassa_bootstrap'))");if((await client.query("SELECT 1 FROM schools LIMIT 1 FOR UPDATE")).rowCount){await client.query("ROLLBACK");return reply.code(409).send({error:"ALREADY_BOOTSTRAPPED"});}
      const ph=await hashPassword(password);const u=(await client.query(`INSERT INTO users(login,email,full_name,password_hash,account_state) VALUES($1,$2,$3,$4,'ACTIVE') RETURNING id,security_version`,[login,email,fullName,ph])).rows[0];
      const s=(await client.query(`INSERT INTO schools(name,school_type,wilaya,moughataa,inspection,academic_year) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[schoolName,schoolType,optionalText(b.wilaya),optionalText(b.moughataa),optionalText(b.inspection),academicYear])).rows[0];await client.query("UPDATE users SET managed_by_school_id=$1 WHERE id=$2",[s.id,u.id]);
      await client.query("INSERT INTO school_memberships(school_id,user_id,status,created_by) VALUES($1,$2,'ACTIVE',$2)",[s.id,u.id]);await client.query("INSERT INTO membership_roles(school_id,user_id,role,created_by) VALUES($1,$2,'DIRECTOR',$2)",[s.id,u.id]);await client.query("SELECT set_config('app.user_id',$1,true)",[u.id]);await client.query("SELECT set_config('app.school_id',$1,true)",[s.id]);await client.query("INSERT INTO school_settings(school_id) VALUES($1)",[s.id]);await client.query("INSERT INTO school_subscriptions(school_id,plan,status,ends_at) VALUES($1,'TRIAL','ACTIVE',now()+interval '30 days')",[s.id]);await audit(client,{userId:u.id,schoolId:s.id},"SCHOOL_BOOTSTRAPPED","school",s.id,{schoolType});await client.query("COMMIT");
      await revokePresentedSession(request);const csrf=await createSession({reply,userId:u.id,activeSchoolId:s.id,securityVersion:u.security_version,userAgent:request.headers["user-agent"],ip:request.ip});return reply.code(201).send({ok:true,csrf,schoolId:s.id});
    }catch(e){try{await client.query("ROLLBACK");}catch{}if(e?.code==="23505")return reply.code(409).send({error:"BOOTSTRAP_CONFLICT"});throw e;}finally{client.release();}
  });

  app.post("/api/auth/register",{config:{rateLimit:{max:5,timeWindow:"1 hour"}}},async(request,reply)=>{
    const b=request.body||{},login=normalizeLogin(b.login),email=normalizeEmail(b.email),fullName=text(b.fullName,{min:2,max:150}),password=String(b.password||"");
    if(!login||login.length<3||login.length>120||!fullName||!validPassword(password))return reply.code(400).send({error:"INVALID_REGISTRATION"});
    const ph=await hashPassword(password);try{const q=await pool.query(`INSERT INTO users(login,email,full_name,password_hash,account_state) VALUES($1,$2,$3,$4,'PENDING') RETURNING id,security_version`,[login,email,fullName,ph]);await revokePresentedSession(request);const csrf=await createSession({reply,userId:q.rows[0].id,activeSchoolId:null,securityVersion:q.rows[0].security_version,userAgent:request.headers["user-agent"],ip:request.ip});return reply.code(201).send({ok:true,csrf,state:"PENDING"});}catch(e){if(e?.code==="23505")return reply.code(409).send({error:"ACCOUNT_ALREADY_EXISTS"});throw e;}
  });

  app.post("/api/auth/login",{config:{rateLimit:{max:8,timeWindow:"15 minutes"}}},async(request,reply)=>{
    const login=normalizeLogin(request.body?.login),password=String(request.body?.password||"");const q=await pool.query(`SELECT id,password_hash,account_state,security_version,locked_until,full_name FROM users WHERE login=$1 LIMIT 1`,[login]);const u=q.rows[0];const ok=await verifyPassword(u?.password_hash||dummyPasswordHash,password);
    if(!u||!ok||["DISABLED","LOCKED"].includes(u.account_state)||(u.locked_until&&new Date(u.locked_until)>new Date())){if(u)await pool.query(`UPDATE users SET failed_login_count=failed_login_count+1,locked_until=CASE WHEN failed_login_count+1>=8 THEN now()+interval '15 minutes' ELSE locked_until END WHERE id=$1`,[u.id]);return reply.code(401).send({error:"INVALID_CREDENTIALS"});}
    await pool.query("UPDATE users SET failed_login_count=0,locked_until=NULL,last_login_at=now(),updated_at=now() WHERE id=$1",[u.id]);const ms=await pool.query("SELECT sm.school_id FROM school_memberships sm JOIN schools sc ON sc.id=sm.school_id WHERE sm.user_id=$1 AND sm.status='ACTIVE' AND sc.active=true ORDER BY sm.created_at",[u.id]);const active=ms.rows.length===1?ms.rows[0].school_id:null;await revokePresentedSession(request);const csrf=await createSession({reply,userId:u.id,activeSchoolId:active,securityVersion:u.security_version,userAgent:request.headers["user-agent"],ip:request.ip});return{ok:true,csrf,user:{id:u.id,fullName:u.full_name,state:u.account_state},schoolSelectionRequired:ms.rows.length>1};
  });

  app.post("/api/auth/logout",async(request,reply)=>{if(request.auth&&!(await requireMutation(request,reply)))return;await destroySession(request,reply);return{ok:true};});
  app.get("/api/auth/me",async(request,reply)=>{if(!(await requireSession(request,reply)))return;let school=null;if(request.auth.schoolId){const q=await pool.query("SELECT id,name,school_type,academic_year,wilaya,moughataa,inspection FROM schools WHERE id=$1 AND active=true",[request.auth.schoolId]);school=q.rows[0]||null;}const platform=await pool.query("SELECT 1 FROM platform_admins WHERE user_id=$1 AND active AND role='SUPER_ADMIN'",[request.auth.userId]);return{isSuperAdmin:platform.rowCount>0,id:request.auth.userId,fullName:request.auth.fullName,login:request.auth.login,email:request.auth.email,state:request.auth.accountState,schoolId:request.auth.schoolId,school,roles:request.auth.roles};});
  app.get("/api/auth/csrf",async(request,reply)=>{if(!(await requireSession(request,reply)))return;const csrf=randomToken(32);await pool.query("UPDATE sessions SET csrf_hash=$1 WHERE id=$2",[tokenHash(csrf),request.auth.sessionId]);return{csrf};});

  app.get("/api/auth/schools",async(request,reply)=>{if(!(await requireSession(request,reply)))return;const q=await pool.query(`SELECT s.id,s.name,s.school_type,s.academic_year,COALESCE(array_agg(mr.role ORDER BY mr.role) FILTER(WHERE mr.role IS NOT NULL),'{}') roles FROM school_memberships sm JOIN schools s ON s.id=sm.school_id LEFT JOIN membership_roles mr ON mr.school_id=sm.school_id AND mr.user_id=sm.user_id WHERE sm.user_id=$1 AND sm.status='ACTIVE' AND s.active=true GROUP BY s.id ORDER BY s.name`,[request.auth.userId]);return{schools:q.rows};});

  app.post("/api/auth/select-school",async(request,reply)=>{if(!(await requireMutation(request,reply)))return;const schoolId=String(request.body?.schoolId||"");if(!isUuid(schoolId))return reply.code(400).send({error:"INVALID_SCHOOL"});const q=await pool.query("SELECT 1 FROM school_memberships sm JOIN schools sc ON sc.id=sm.school_id WHERE sm.school_id=$1 AND sm.user_id=$2 AND sm.status='ACTIVE' AND sc.active=true",[schoolId,request.auth.userId]);if(!q.rowCount)return reply.code(403).send({error:"SCHOOL_ACCESS_DENIED"});const sv=(await pool.query("SELECT security_version FROM users WHERE id=$1",[request.auth.userId])).rows[0]?.security_version;await revokePresentedSession(request);const csrf=await createSession({reply,userId:request.auth.userId,activeSchoolId:schoolId,securityVersion:sv,userAgent:request.headers["user-agent"],ip:request.ip});return{ok:true,csrf};});

  app.post("/api/auth/step-up",{config:{rateLimit:{max:5,timeWindow:"15 minutes"}}},async(request,reply)=>{if(!(await requireMutation(request,reply)))return;const r=await pool.query("SELECT password_hash FROM users WHERE id=$1",[request.auth.userId]);if(!(await verifyPassword(r.rows[0]?.password_hash||dummyPasswordHash,String(request.body?.password||""))))return reply.code(401).send({error:"REAUTH_FAILED"});await pool.query("UPDATE sessions SET step_up_until=now()+interval '10 minutes' WHERE id=$1",[request.auth.sessionId]);return{ok:true};});

  app.post("/api/auth/password/forgot",{config:{rateLimit:{max:3,timeWindow:"1 hour"}}},async request=>{const key=normalizeLogin(request.body?.loginOrEmail);const r=await pool.query("SELECT id FROM users WHERE login=$1 OR email=$1 LIMIT 1",[key]);if(r.rows[0]){const token=randomToken(32);await pool.query("UPDATE password_reset_requests SET used_at=COALESCE(used_at,now()) WHERE user_id=$1 AND used_at IS NULL",[r.rows[0].id]);await pool.query("INSERT INTO password_reset_requests(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '20 minutes')",[r.rows[0].id,tokenHash(token)]);/* Delivery integration intentionally external. */}return{ok:true,message:"IF_ACCOUNT_EXISTS_RECOVERY_STARTED"};});

  app.post("/api/auth/password/reset",{config:{rateLimit:{max:5,timeWindow:"30 minutes"}}},async(request,reply)=>{const token=String(request.body?.token||"").trim(),password=String(request.body?.newPassword||"");if(token.length<20||!validPassword(password))return reply.code(400).send({error:"INVALID_RESET"});const client=await pool.connect();try{await client.query("BEGIN");const q=await client.query(`SELECT pr.id,pr.user_id FROM password_reset_requests pr WHERE pr.token_hash=$1 AND pr.used_at IS NULL AND pr.expires_at>now() FOR UPDATE`,[tokenHash(token)]);if(!q.rows[0]){await client.query("ROLLBACK");return reply.code(400).send({error:"INVALID_RESET"});}const ph=await hashPassword(password);await client.query("UPDATE users SET password_hash=$1,security_version=security_version+1,failed_login_count=0,locked_until=NULL,updated_at=now() WHERE id=$2",[ph,q.rows[0].user_id]);await client.query("UPDATE password_reset_requests SET used_at=now() WHERE id=$1",[q.rows[0].id]);await client.query("UPDATE sessions SET revoked_at=now() WHERE user_id=$1",[q.rows[0].user_id]);await client.query("COMMIT");reply.clearCookie("__Host-mm_session",{path:"/"});reply.clearCookie("mm_session",{path:"/"});return{ok:true};}catch(e){try{await client.query("ROLLBACK");}catch{}throw e;}finally{client.release();}});

  app.post("/api/invites/redeem",{config:{rateLimit:{max:8,timeWindow:"30 minutes"}}},async(request,reply)=>{if(!(await requireMutation(request,reply)))return;const code=String(request.body?.code||"").trim();if(code.length<20)return reply.code(400).send({error:"INVALID_OR_EXPIRED_CODE"});const client=await pool.connect();let inv;try{await client.query("BEGIN");const f=await client.query(`SELECT * FROM access_invites WHERE code_hash=$1 AND revoked_at IS NULL AND expires_at>now() AND used_count<max_uses FOR UPDATE`,[tokenHash(code)]);inv=f.rows[0];if(!inv||!(await client.query("SELECT 1 FROM schools WHERE id=$1 AND active=true",[inv.school_id])).rowCount){await client.query("ROLLBACK");return reply.code(400).send({error:"INVALID_OR_EXPIRED_CODE"});}await client.query("SELECT set_config('app.user_id',$1,true)",[request.auth.userId]);await client.query("SELECT set_config('app.school_id',$1,true)",[inv.school_id]);await client.query("SELECT set_config('app.invite_id',$1,true)",[inv.id]);if(inv.target_login&&normalizeLogin(inv.target_login)!==normalizeLogin(request.auth.login)){await client.query("ROLLBACK");return reply.code(403).send({error:"CODE_NOT_FOR_THIS_ACCOUNT"});}if(inv.target_email&&normalizeEmail(inv.target_email)!==normalizeEmail(request.auth.email)){await client.query("ROLLBACK");return reply.code(403).send({error:"CODE_NOT_FOR_THIS_ACCOUNT"});}
      await client.query(`INSERT INTO school_memberships(school_id,user_id,status,created_by) VALUES($1,$2,'ACTIVE',$3) ON CONFLICT(school_id,user_id) DO UPDATE SET status='ACTIVE',revoked_at=NULL`,[inv.school_id,request.auth.userId,inv.created_by]);await client.query(`INSERT INTO membership_roles(school_id,user_id,role,created_by) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING`,[inv.school_id,request.auth.userId,inv.role,inv.created_by]);const perms=Array.isArray(inv.permissions)?inv.permissions.filter(p=>PERMISSIONS.includes(p)):[];for(const p of perms)await client.query(`INSERT INTO permission_grants(school_id,user_id,permission,class_id,subject_id,granted_by) VALUES($1,$2,$3,$4,$5,$6)`,[inv.school_id,request.auth.userId,p,inv.class_id,inv.subject_id,inv.created_by]);
      const studentIds=Array.isArray(inv.student_ids)?[...new Set(inv.student_ids.filter(isUuid))]:[];if(inv.role==="GUARDIAN"&&studentIds.length){const valid=(await client.query("SELECT id,class_id FROM students WHERE school_id=$1 AND id=ANY($2::uuid[])",[inv.school_id,studentIds])).rows;if(valid.length!==studentIds.length){await client.query("ROLLBACK");return reply.code(400).send({error:"INVITE_SCOPE_INVALID"});}for(const s of valid)await client.query(`INSERT INTO guardian_student_links(school_id,guardian_user_id,student_id,class_id,created_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(guardian_user_id,student_id) DO UPDATE SET active=true`,[inv.school_id,request.auth.userId,s.id,s.class_id,inv.created_by]);}
      await client.query("UPDATE access_invites SET used_count=used_count+1,used_at=now() WHERE id=$1",[inv.id]);await client.query("UPDATE users SET account_state='ACTIVE',updated_at=now() WHERE id=$1",[request.auth.userId]);await audit(client,{userId:request.auth.userId,schoolId:inv.school_id},"ACCESS_INVITE_REDEEMED","invite",inv.id,{role:inv.role});await client.query("COMMIT");
    }catch(e){try{await client.query("ROLLBACK");}catch{}throw e;}finally{client.release();}
    const sv=(await pool.query("SELECT security_version FROM users WHERE id=$1",[request.auth.userId])).rows[0]?.security_version;await revokePresentedSession(request);const csrf=await createSession({reply,userId:request.auth.userId,activeSchoolId:inv.school_id,securityVersion:sv,userAgent:request.headers["user-agent"],ip:request.ip});return{ok:true,csrf,schoolId:inv.school_id,role:inv.role};
  });
}
